<a href="https://colab.research.google.com/github/agamthind96/TensorFlow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook, we are going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we are going to cover :
* Introduction to Tensors.
* Getting information from Tensors.
* Manipulating Tensors.
* Tensors & Numpy.
* Using @tf.function (a way to speed up your regular Pyhton functions)
* Using GPU's with TensorFlow(or TPU's)
* Exercises to try for yourself.

##Introduction to Tensors

In [ ]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check number of dimensions of tensor.
scalar.ndim

0

In [ ]:
# Create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensions of vector.
vector.ndim

1

In [ ]:
# Create a matrix (it has more than 1 dimensions)
matrix = tf.constant([[7,10],
                     [3,4]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 3,  4]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix by specifying the data type.
another_matrix = tf.constant([[1,2],
                             [3,4]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor.
tensor = tf.constant([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                      [[10,11,12],
                      [13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

 What we have created so far :

 * Scalar : A single number
 * Vector : A number with direction.
 * Matrix : A 2-D array of numbers.
 * Tensors : n-D array of numbers(0-D tensor is scalar, 1-D tensor is vector)

### Creating tensors with **tf.Variable**

In [ ]:
# Create a same tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Assigning different value in a changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

**Note** : Rarely in practise you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlowdoes this for you.However, if in doubt, use **tf.constant** and change it later if needed.

### Creating random tensors
Random tensors are tensors of some arbitrary size which contains random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a Tensor

In [ ]:
# Shuffle the tensor
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Global and Opeartion seeds

In [ ]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # Global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

### Other ways to make tensors.

In [ ]:
# Create a tensor having all elements as 1
tf.ones(shape = [5,5], dtype = tf.int32)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [ ]:
# Create a tensor of zeros
tf.zeros(shape=(4,12), dtype=tf.int32)

<tf.Tensor: shape=(4, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

### Turn Numpy array into tensors.

The main difference between Numpy arrays and TensorFlow tensors is that tensors can run on GPU (numerical computation is very fast)

In [ ]:
# Converting numpy arrays into tensors.
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tensor_A = tf.constant(numpy_A)
tensor_A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
tensor_B = tf.constant(numpy_A, dtype = tf.int32, shape = (2,3,4), name = "Reshaped Tensor" )
tensor_B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

We can have tensor details in the form of following attributes :
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor (having 4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,1,2), dtype = tf.float32)
rank_4_tensor


<tf.Tensor: shape=(2, 3, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]],


       [[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 1, 2), dtype=float32, numpy=
array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][0][0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 1, 2])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
def tensor_details(tensor):
  """
  Shows different details obtained from tensor
  """
  show_details = {"Shape of tensor : " : tensor.shape,
                  "Rank of tensor : " : tensor.ndim,
                  "Size of tensor : " : tf.size(tensor).numpy(),
                  "Data Type of tensor : " : tensor.dtype,
                  "Elements along 0 axis for tensor : " : tensor.shape[0]}

  return show_details


In [ ]:
tensor_details(rank_4_tensor)

{'Data Type of tensor : ': tf.float32,
 'Elements along 0 axis for tensor : ': 2,
 'Rank of tensor : ': 4,
 'Shape of tensor : ': TensorShape([2, 3, 1, 2]),
 'Size of tensor : ': 12}

### Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
rank_4_tensor[ :2, :1, :1, :2]

<tf.Tensor: shape=(2, 1, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]]],


       [[[0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[ : , : , : , : ]

<tf.Tensor: shape=(2, 3, 1, 2), dtype=float32, numpy=
array([[[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]],


       [[[0., 0.]],

        [[0., 0.]],

        [[0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
rank_2_tensor[ : , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
rank_2_tensor[0, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
# Add extra dimension to rank_2_tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor, axis=-1, name = rank_3_tensor)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [ ]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

In [ ]:
# You can add values to tensor using basic addition operator
add_tensor = tf.constant([[1,2],
                          [3,4]])
add_tensor + 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[101, 102],
       [103, 104]], dtype=int32)>

In [ ]:
# Multiplication
multiply_tensor = add_tensor * 100
multiply_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100, 200],
       [300, 400]], dtype=int32)>

In [ ]:
# We can use the tensorflow built in function too
tf.multiply(add_tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
tf.add(add_tensor, add_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

### Matrix Multiplication

In Machine Learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
tf.matmul(add_tensor, multiply_tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [ ]:
tf.matmul(add_tensor, multiply_tensor, transpose_b = True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 500, 1100],
       [1100, 2500]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator "@"
add_tensor @ multiply_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [ ]:
# Create two (3*2  tensors
X = tf.constant([[1,2],
                [3,4],
                [5,6]])

Y = tf.constant([[7,8],
                [9,10],
                [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# Do matrix multiplication
tf.matmul(X,Y, transpose_b = True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X,Y,transpose_a = True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Dot Product

In [ ]:
tf.tensordot(X,tf.transpose(Y), axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  9, 11],
         [ 8, 10, 12]],

        [[14, 18, 22],
         [16, 20, 24]]],


       [[[21, 27, 33],
         [24, 30, 36]],

        [[28, 36, 44],
         [32, 40, 48]]],


       [[[35, 45, 55],
         [40, 50, 60]],

        [[42, 54, 66],
         [48, 60, 72]]]], dtype=int32)>

In [ ]:
a = tf.constant([[1,2,3],
                 [10,20,30]])
b = tf.constant([[3,4,5],
                 [100,200,300]])
tf.tensordot(a,b,axes=0)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[   3,    4,    5],
         [ 100,  200,  300]],

        [[   6,    8,   10],
         [ 200,  400,  600]],

        [[   9,   12,   15],
         [ 300,  600,  900]]],


       [[[  30,   40,   50],
         [1000, 2000, 3000]],

        [[  60,   80,  100],
         [2000, 4000, 6000]],

        [[  90,  120,  150],
         [3000, 6000, 9000]]]], dtype=int32)>

### Changing the datatype of tensor


In [ ]:
B = tf.constant([1.2,3.4])
B.dtype


tf.float32

In [ ]:
C = tf.constant([1,2])
C.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.2, 3.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-3,-11,10])
tf.abs(D)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3, 11, 10], dtype=int32)>

# Let's go through following forms of aggregation.

* Get the minimum.
* Get the maximum.
* Get the mean of the tensor.
* Get the sum of tensor.

In [ ]:
tensor_1 = tf.constant([[1,2,3,4,5],
                       [6,7,8,9,10]])
tensor_1

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]], dtype=int32)>

In [ ]:
# Create a random tensor with values between 0 and 100 and with size of 50
E = tf.constant(np.random.randint(0,100,size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67, 51, 90,  7,  5,  7, 69, 94, 80, 85, 13, 31, 62, 67, 34,  7, 18,
       12, 93, 32,  6, 33, 64, 70, 58, 66, 22, 33, 46, 64, 97, 76, 57, 16,
       49, 76, 96, 41, 54, 83, 91, 45, 52,  1, 27, 26, 25, 54, 63,  5])>

In [ ]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2420>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=827>

In [ ]:
  # Find the standard deviation
  E = tf.cast(E, dtype=tf.float32)
  E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([67., 51., 90.,  7.,  5.,  7., 69., 94., 80., 85., 13., 31., 62.,
       67., 34.,  7., 18., 12., 93., 32.,  6., 33., 64., 70., 58., 66.,
       22., 33., 46., 64., 97., 76., 57., 16., 49., 76., 96., 41., 54.,
       83., 91., 45., 52.,  1., 27., 26., 25., 54., 63.,  5.],
      dtype=float32)>

In [ ]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float32, numpy=28.76178>

### Find the positional maximum and minimum.

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([67., 51., 90.,  7.,  5.,  7., 69., 94., 80., 85., 13., 31., 62.,
       67., 34.,  7., 18., 12., 93., 32.,  6., 33., 64., 70., 58., 66.,
       22., 33., 46., 64., 97., 76., 57., 16., 49., 76., 96., 41., 54.,
       83., 91., 45., 52.,  1., 27., 26., 25., 54., 63.,  5.],
      dtype=float32)>

In [ ]:
tf.random.set_seed(42)
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([67., 51., 90.,  7.,  5.,  7., 69., 94., 80., 85., 13., 31., 62.,
       67., 34.,  7., 18., 12., 93., 32.,  6., 33., 64., 70., 58., 66.,
       22., 33., 46., 64., 97., 76., 57., 16., 49., 76., 96., 41., 54.,
       83., 91., 45., 52.,  1., 27., 26., 25., 54., 63.,  5.],
      dtype=float32)>

In [ ]:
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
E[tf.argmax(E)] == tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor 
tf.random.set_seed(42)
F = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
F = tf.constant(tf.random.uniform(shape=[1,1,1,1,50]))
F

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
F.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
F_squeezed = tf.squeeze(F, axis=[0,1,2])
F_squeezed

<tf.Tensor: shape=(1, 50), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]],
      dtype=float32)>

In [ ]:
F_squeezed_1 = tf.squeeze(F)
F_squeezed_1

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

### One hot encoded tensors

In [ ]:
# Create a random list
some_list = [0,1,2,3]

# One Hot encode our list
tf.one_hot(some_list, depth=4, on_value = 100, off_value = 0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[100,   0,   0,   0],
       [  0, 100,   0,   0],
       [  0,   0, 100,   0],
       [  0,   0,   0, 100]], dtype=int32)>

### Square, Log, Square root

In [ ]:
# Create a new tensor
G = tf.range(1,10)
G

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(G)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
G = tf.cast(G, dtype=tf.float32)

In [ ]:
G

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
tf.sqrt(G)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(G)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow interacts beautifully with Numpy arrays

In [ ]:
# Create a tensor directly from Numpy array
J = tf.constant(np.array([3.,6.,9.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 6., 9.])>

In [ ]:
# Convert our tensor back into Numpy array
np.array(J), type(np.array(J))

(array([3., 6., 9.]), numpy.ndarray)

In [ ]:
J.numpy()

array([3., 6., 9.])

In [ ]:
type(J.numpy())

numpy.ndarray

In [ ]:
J[0]

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [ ]:
J.numpy()[0]

3.0

In [ ]:
# The default types of each are different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU's

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jul 26 11:46:08 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.42.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P0    29W /  70W |    224MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------